---
- name: Disable Windows Password Complexity Policy
  hosts: windows
  gather_facts: no
  tasks:
    - name: Disable password complexity requirement
      win_command: >
        secedit.exe /export /cfg C:\Temp\secpol.cfg
    - name: Set PasswordComplexity to 0 in exported config
      win_lineinfile:
        path: C:\Temp\secpol.cfg
        regexp: '^PasswordComplexity ='
        line: 'PasswordComplexity = 0'
    - name: Import modified security policy
      win_command: >
        secedit.exe /configure /db secedit.sdb /cfg C:\Temp\secpol.cfg /areas SECURITYPOLICY
    - name: Remove temp config file
      win_file:
        path: C:\Temp\secpol.cfg
        state: absent
