---
- name: Disable Windows Update Service
  hosts: windows
  gather_facts: no
  tasks:
    - name: Stop Windows Update service
      win_service:
        name: wuauserv
        state: stopped
        start_mode: disabled
      become: yes
      become_method: runas
      become_user: Ansible
