---
- name: Disable Windows Password Complexity Policy
  hosts: windows
  gather_facts: no
  tasks:
    - name: Ensure C:\Temp exists
      win_file:
        path: C:\Temp
        state: directory
    - name: Disable password complexity requirement
      win_command: >
        secedit.exe /export /cfg C:\Temp\secpol.cfg
      become: yes
      become_method: runas
      become_user: Ansible
    - name: Set PasswordComplexity to 0 in exported config
      win_lineinfile:
        path: C:\Temp\secpol.cfg
        regexp: '^PasswordComplexity ='
        line: 'PasswordComplexity = 0'
      become: yes
      become_method: runas
      become_user: Ansible
    - name: Import modified security policy
      win_command: >
        secedit.exe /configure /db secedit.sdb /cfg C:\Temp\secpol.cfg /areas SECURITYPOLICY
      become: yes
      become_method: runas
      become_user: Ansible
    - name: Remove temp config file
      win_file:
        path: C:\Temp\secpol.cfg
        state: absent
      become: yes
      become_method: runas
      become_user: Ansible
